# Generated by Django 4.1.2 on 2022-12-17 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnelPlanet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employer',
        ),
        migrations.AddField(
            model_name='company',
            name='companyName',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnelPlanet.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='hoursWorked',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
