# Generated by Django 4.1.2 on 2022-12-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnelPlanet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_employer',
            new_name='isEmployer',
        ),
    ]
