# Generated by Django 4.1.2 on 2022-12-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnelPlanet', '0002_remove_company_employer_company_companyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
