# Generated by Django 4.1.2 on 2022-12-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnelPlanet', '0002_rename_is_employer_user_isemployer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='end',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='start',
        ),
        migrations.AddField(
            model_name='availability',
            name='shift',
            field=models.CharField(default='All', max_length=10),
        ),
    ]
