# Generated by Django 4.1.2 on 2022-12-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnelPlanet', '0003_remove_availability_end_remove_availability_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='shift',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
