# Generated by Django 4.1.2 on 2022-12-17 17:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('personnelPlanet', '0003_alter_company_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payRate',
            field=models.FloatField(default=7.45),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='(555) 555 5555', max_length=128, region=None),
        ),
    ]
