# Generated by Django 4.1.2 on 2022-12-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnelPlanet', '0006_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='company',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
