# Generated by Django 4.1.2 on 2022-12-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnelPlanet', '0008_alter_clock_clockout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='clockOut',
            field=models.DateField(blank=True, null=True),
        ),
    ]
