# Generated by Django 4.1.2 on 2022-12-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnelPlanet', '0011_rename_touser_messages_comapny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='comapny',
            field=models.CharField(max_length=25),
        ),
    ]
