# Generated by Django 4.1.2 on 2022-12-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnelPlanet', '0012_alter_messages_comapny'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='comapny',
            new_name='company',
        ),
    ]
