# Generated by Django 4.1.2 on 2022-12-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnelPlanet', '0013_rename_comapny_messages_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='fromUser',
            field=models.CharField(max_length=25),
        ),
    ]
