# Generated by Django 4.1.2 on 2022-12-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnelPlanet', '0014_alter_messages_fromuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='fromUserId',
            field=models.IntegerField(default=0),
        ),
    ]
