# Generated by Django 4.0 on 2023-01-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnelPlanet', '0016_tasks_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='company',
            field=models.CharField(default='Company', max_length=25),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='assignedTo',
            field=models.CharField(default='Team', max_length=150),
        ),
    ]
