# Generated by Django 4.0 on 2023-01-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnelPlanet', '0017_tasks_company_alter_tasks_assignedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='weekEnd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='weekStart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
