# Generated by Django 4.0 on 2023-01-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnelPlanet', '0018_schedule_weekend_schedule_weekstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totalHours',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
