# Generated by Django 4.0 on 2023-01-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnelPlanet', '0019_user_totalhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='assignedToId',
            field=models.IntegerField(default=0),
        ),
    ]
